name: Metrics

on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
#  activity-community:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: lowlighter/metrics@latest
#        with:
#          token: ${{ secrets.METRICS_TOKEN }}
#          user: viren-nadkarni
#          template: classic
#          config_timezone: Asia/Kolkata
#
#          base: activity, community
#          filename: activity-community.svg

  iso-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: viren-nadkarni
          template: classic
          config_timezone: Asia/Kolkata

          base: ""
          filename: iso-calendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: viren-nadkarni
          template: classic
          config_timezone: Asia/Kolkata

          base: ""
          repositories_affiliations: ""
          repositories_skipped: >-
            viren-nadkarni/bvd-snort, viren-nadkarni/masters-thesis, viren-nadkarni/cth-vehsys,
            viren-nadkarni/cpython-internals, viren-nadkarni/two-degrees, viren-nadkarni/watson,
            viren-nadkarni/pintos, viren-nadkarni/dotfiles, viren-nadkarni/fyp, viren-nadkarni/codu,
            levfinder/bernard, Vilddjur/gbgStartupHack2019

          filename: habits.svg
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes

  followup-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: viren-nadkarni
          template: classic
          config_timezone: Asia/Kolkata

          base: ""
          repositories_affiliations: ""
          repositories_skipped: >-
            viren-nadkarni/bvd-snort, viren-nadkarni/masters-thesis, viren-nadkarni/cth-vehsys,
            viren-nadkarni/cpython-internals, viren-nadkarni/two-degrees, viren-nadkarni/watson,
            viren-nadkarni/pintos, viren-nadkarni/dotfiles, viren-nadkarni/fyp, viren-nadkarni/codu,
            levfinder/bernard, Vilddjur/gbgStartupHack2019

          filename: followup-languages.svg
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css

#  repositories:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: lowlighter/metrics@latest
#        with:
#          token: ${{ secrets.METRICS_TOKEN }}
#          user: viren-nadkarni
#          template: classic
#          config_timezone: Asia/Kolkata
#
#          base: repositories
#          filename: repositories.svg

  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: viren-nadkarni
          template: classic
          config_timezone: Asia/Kolkata

          base: header
          filename: header.svg

  lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: viren-nadkarni
          template: classic
          config_timezone: Asia/Kolkata

          base: ""
          repositories_affiliations: ""
          repositories_skipped: >-
            viren-nadkarni/bvd-snort, viren-nadkarni/masters-thesis, viren-nadkarni/cth-vehsys,
            viren-nadkarni/cpython-internals, viren-nadkarni/two-degrees, viren-nadkarni/watson,
            viren-nadkarni/pintos, viren-nadkarni/dotfiles, viren-nadkarni/fyp, viren-nadkarni/codu,
            levfinder/bernard, Vilddjur/gbgStartupHack2019

          filename: lines.svg
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_repositories_limit: 5

#  achievements:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: lowlighter/metrics@latest
#        with:
#          token: ${{ secrets.METRICS_TOKEN }}
#          user: viren-nadkarni
#          template: classic
#          config_timezone: Asia/Kolkata
#
#          base: achievements
#          filename: achievements.svg
#          plugin_achievements: yes
#          plugin_achievements_display: compact
